# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170707_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='slug',
            field=models.SlugField(default='ninja'),
        ),
    ]
