# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profpic', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
