# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170719_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(max_length=40),
        ),
    ]
