# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170719_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['-instrument']},
        ),
    ]
